***Задание 1***

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

n = 10
i = 1
myarr = np.empty(0, int)
while i <= n:
    myarr = np.append(myarr, int(n-i))
    i = i + 1

print(type(myarr))
myarr

<class 'numpy.ndarray'>


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
#второй вариант по проще
myarr2 = np.arange( 0, n )
myarr2 = myarr2[::-1]
print(type(myarr2))
myarr2

<class 'numpy.ndarray'>


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
# третий вариант самый простой

myarr3 = np.arange( 0, n )
print(type(myarr3))
np.flipud(myarr3)

<class 'numpy.ndarray'>


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

***Задание 2***

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [34]:
n2 = 7

x = np.arange( 0, n2 )
x = np.flip(x, axis=0)

mat = np.diag(x, k=0)
print(type(mat))
mat

<class 'numpy.ndarray'>


array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [42]:
total_sum = 0
i = 0

for m in mat:
    total_sum =  total_sum + m[i]
    i = i +1
total_sum

21

***Задание 3***

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [59]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [60]:
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [61]:
x = 0.46666667
y = 3.84444444
z = -5.55555556

In [62]:
print(4*x + 2*y + z)
print(x + 3*y)
print(5*y + 4*z)

4.0
11.999999990000001
-3.0000000399999998


In [63]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True